const axios = require("axios");
const readline = require("readline");

// Setup readline to get user input
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Ask the user for a prompt
rl.question("Enter your workflow description: ", async (userPrompt) => {
  try {
    //1️⃣ Call GPT-2 FastAPI server
    const res = await axios.post("http://localhost:8000/generate", { prompt: userPrompt });
    const workflowDescription = res.data.text;
    console.log("\nWorkflow description generated by GPT-2:\n", workflowDescription);

    // 2️⃣ Convert description to n8n workflow
    // Here, you could implement a parser if GPT-2 outputs JSON directly.
    // For now, we'll use a simple static example as placeholder.
    const workflowPayload = {
      name: "Generated Workflow",
      nodes: [
        {
          name: "Trigger Node",
          type: "n8n-nodes-base.start",
          position: [250, 300],
          parameters: {}
        },
        {
          name: "Email Node",
          type: "n8n-nodes-base.sendEmail",
          position: [500, 300],
          parameters: {
            email: "customer@example.com",
            subject: "New Order",
            message: workflowDescription
          }
        }
      ],
      connections: {
        "Trigger Node": {
          main: [[{ node: "Email Node", type: "main", index: 0 }]]
        }
      },
      settings: {}
    };

    // 3️⃣ Create workflow in n8n
    const response = await axios.post(
      "http://localhost:5678/api/v1/workflows",
      workflowPayload,
      {
        headers: {
          "X-N8N-API-KEY": process.env.N8N_API_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0YjQxYzJhMy1mOTNlLTRkYmMtYWY5Yi1mMDY2ODc3NmQ0NTIiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzU5MTMwOTYwLCJleHAiOjE3NjE3MTA0MDB9.ZD2ChMIRYALh1bPvB0wgglrvH58EDokt6G7vbnqCYdQ"
        }
      }
    );

    const workflowId = response.data.id;
    console.log(`\n✅ Workflow created successfully!`);
    console.log(`Open it here: http://localhost:5678/workflow/${workflowId}`);

  } catch (err) {
    console.error("Error:", err.response?.data || err.message);
  } finally {
    rl.close();
  }
});
